version: "3"

services:
  #PHP
  php-fpm:
    build: ./php-fpm
    container_name: np_php-fpm
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - mysql

  #Nginx
  nginx:
    image: nginx:1.15
    container_name: np_nginx
    volumes:
      - ../:/app
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  #MySQL
  mysql:
    image: mysql:5.7
    container_name: np_mysql
    volumes:
      - ../var/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - '../.env'
